package cn.com.reey.VMSweb.entity;

// Generated 2016-5-5 16:53:14 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Application generated by hbm2java
 */
@Entity
@Table(name = "application", catalog = "vms")
public class Application implements java.io.Serializable {

	private Integer applicationid;
	private Users usersByApplicationuser;
	private Users usersByApplicationsendpeople;
	private Vehicle vehicle;
	private Driver driver;
	private String applicationreason;
	private String applicationstartposition;
	private String applicationendposition;
	private Date applicationstarttime;
	private Date applicationendtime;
	private Float applicationdistance;
	private String applicationnote;
	private Integer applicationispass;

	public Application() {
	}

	public Application(Users usersByApplicationuser,
			Users usersByApplicationsendpeople, Vehicle vehicle, Driver driver,
			String applicationreason, String applicationstartposition,
			String applicationendposition, Date applicationstarttime,
			Date applicationendtime, Float applicationdistance,
			String applicationnote, Integer applicationispass) {
		this.usersByApplicationuser = usersByApplicationuser;
		this.usersByApplicationsendpeople = usersByApplicationsendpeople;
		this.vehicle = vehicle;
		this.driver = driver;
		this.applicationreason = applicationreason;
		this.applicationstartposition = applicationstartposition;
		this.applicationendposition = applicationendposition;
		this.applicationstarttime = applicationstarttime;
		this.applicationendtime = applicationendtime;
		this.applicationdistance = applicationdistance;
		this.applicationnote = applicationnote;
		this.applicationispass = applicationispass;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "applicationid", unique = true, nullable = false)
	public Integer getApplicationid() {
		return this.applicationid;
	}

	public void setApplicationid(Integer applicationid) {
		this.applicationid = applicationid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "applicationuser")
	public Users getUsersByApplicationuser() {
		return this.usersByApplicationuser;
	}

	public void setUsersByApplicationuser(Users usersByApplicationuser) {
		this.usersByApplicationuser = usersByApplicationuser;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "applicationsendpeople")
	public Users getUsersByApplicationsendpeople() {
		return this.usersByApplicationsendpeople;
	}

	public void setUsersByApplicationsendpeople(
			Users usersByApplicationsendpeople) {
		this.usersByApplicationsendpeople = usersByApplicationsendpeople;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "applicationvehicle")
	public Vehicle getVehicle() {
		return this.vehicle;
	}

	public void setVehicle(Vehicle vehicle) {
		this.vehicle = vehicle;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "applicationdriver")
	public Driver getDriver() {
		return this.driver;
	}

	public void setDriver(Driver driver) {
		this.driver = driver;
	}

	@Column(name = "applicationreason")
	public String getApplicationreason() {
		return this.applicationreason;
	}

	public void setApplicationreason(String applicationreason) {
		this.applicationreason = applicationreason;
	}

	@Column(name = "applicationstartposition")
	public String getApplicationstartposition() {
		return this.applicationstartposition;
	}

	public void setApplicationstartposition(String applicationstartposition) {
		this.applicationstartposition = applicationstartposition;
	}

	@Column(name = "applicationendposition")
	public String getApplicationendposition() {
		return this.applicationendposition;
	}

	public void setApplicationendposition(String applicationendposition) {
		this.applicationendposition = applicationendposition;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "applicationstarttime", length = 19)
	public Date getApplicationstarttime() {
		return this.applicationstarttime;
	}

	public void setApplicationstarttime(Date applicationstarttime) {
		this.applicationstarttime = applicationstarttime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "applicationendtime", length = 19)
	public Date getApplicationendtime() {
		return this.applicationendtime;
	}

	public void setApplicationendtime(Date applicationendtime) {
		this.applicationendtime = applicationendtime;
	}

	@Column(name = "applicationdistance", precision = 12, scale = 0)
	public Float getApplicationdistance() {
		return this.applicationdistance;
	}

	public void setApplicationdistance(Float applicationdistance) {
		this.applicationdistance = applicationdistance;
	}

	@Column(name = "applicationnote")
	public String getApplicationnote() {
		return this.applicationnote;
	}

	public void setApplicationnote(String applicationnote) {
		this.applicationnote = applicationnote;
	}

	@Column(name = "applicationispass")
	public Integer getApplicationispass() {
		return this.applicationispass;
	}

	public void setApplicationispass(Integer applicationispass) {
		this.applicationispass = applicationispass;
	}

}
