package cn.com.reey.VMSweb.entity;

// Generated 2016-5-5 16:53:14 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

import com.alibaba.fastjson.annotation.JSONField;

/**
 * Permission generated by hbm2java
 */
@Entity
@Table(name = "permission", catalog = "vms")
public class Permission implements java.io.Serializable {

	private Integer permissionid;
	private String permissionname;
	private String permissionnote;
	@JSONField(serialize = false)
	private Set<Role> roles = new HashSet<Role>(0);

	public Permission() {
	}

	public Permission(String permissionname, String permissionnote,
			Set<Role> roles) {
		this.permissionname = permissionname;
		this.permissionnote = permissionnote;
		this.roles = roles;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "permissionid", unique = true, nullable = false)
	public Integer getPermissionid() {
		return this.permissionid;
	}

	public void setPermissionid(Integer permissionid) {
		this.permissionid = permissionid;
	}

	@Column(name = "permissionname", length = 32)
	public String getPermissionname() {
		return this.permissionname;
	}

	public void setPermissionname(String permissionname) {
		this.permissionname = permissionname;
	}

	@Column(name = "permissionnote")
	public String getPermissionnote() {
		return this.permissionnote;
	}

	public void setPermissionnote(String permissionnote) {
		this.permissionnote = permissionnote;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "permissions")
	public Set<Role> getRoles() {
		return this.roles;
	}

	public void setRoles(Set<Role> roles) {
		this.roles = roles;
	}

}
