package cn.com.reey.VMSweb.entity;

// Generated 2016-5-5 16:53:14 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.alibaba.fastjson.annotation.JSONField;

/**
 * Vehicle generated by hbm2java
 */
@Entity
@Table(name = "vehicle", catalog = "vms")
public class Vehicle implements java.io.Serializable {

	private Integer vehicleid;
	private String vehicleplatenumber;
	private String vehicleinfo;
	private String vehiclephoto;
	private Integer vehiclestate;
	private String vehiclenote;
	@JSONField(serialize = false)
	private Set<Application> applications = new HashSet<Application>(0);

	public Vehicle() {
	}

	public Vehicle(String vehicleplatenumber, String vehicleinfo,
			String vehiclephoto, Integer vehiclestate, String vehiclenote,
			Set<Application> applications) {
		this.vehicleplatenumber = vehicleplatenumber;
		this.vehicleinfo = vehicleinfo;
		this.vehiclephoto = vehiclephoto;
		this.vehiclestate = vehiclestate;
		this.vehiclenote = vehiclenote;
		this.applications = applications;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "vehicleid", unique = true, nullable = false)
	public Integer getVehicleid() {
		return this.vehicleid;
	}

	public void setVehicleid(Integer vehicleid) {
		this.vehicleid = vehicleid;
	}

	@Column(name = "vehicleplatenumber", length = 64)
	public String getVehicleplatenumber() {
		return this.vehicleplatenumber;
	}

	public void setVehicleplatenumber(String vehicleplatenumber) {
		this.vehicleplatenumber = vehicleplatenumber;
	}

	@Column(name = "vehicleinfo")
	public String getVehicleinfo() {
		return this.vehicleinfo;
	}

	public void setVehicleinfo(String vehicleinfo) {
		this.vehicleinfo = vehicleinfo;
	}

	@Column(name = "vehiclephoto")
	public String getVehiclephoto() {
		return this.vehiclephoto;
	}

	public void setVehiclephoto(String vehiclephoto) {
		this.vehiclephoto = vehiclephoto;
	}

	@Column(name = "vehiclestate")
	public Integer getVehiclestate() {
		return this.vehiclestate;
	}

	public void setVehiclestate(Integer vehiclestate) {
		this.vehiclestate = vehiclestate;
	}

	@Column(name = "vehiclenote")
	public String getVehiclenote() {
		return this.vehiclenote;
	}

	public void setVehiclenote(String vehiclenote) {
		this.vehiclenote = vehiclenote;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vehicle")
	public Set<Application> getApplications() {
		return this.applications;
	}

	public void setApplications(Set<Application> applications) {
		this.applications = applications;
	}

}
